_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fr
module:
  admin_toolbar: 0
  authorization: 0
  authorization_drupal_roles: 0
  auto_entitylabel: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  config: 0
  config_translation: 0
  contextual: 0
  cshs: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  formblock: 0
  image: 0
  inventaire_conteneur: 0
  inventaire_ghs: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  ldap_authentication: 0
  ldap_authorization: 0
  ldap_query: 0
  ldap_servers: 0
  ldap_user: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_export: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  search_api: 0
  search_api_solr: 0
  svg_image_field: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  manage_display: 1
  externalauth: 10
  views: 10
  minimal: 1000
theme:
  claro: 0
  laboratoire: 0
profile: minimal
