1:
  id:
    value: '1'
  uuid:
    value: 7d809031-8f6d-4e12-88dc-3feaff8dc47d
  revision_id:
    value: '1'
  langcode:
    value: fr
  bundle:
    value: menu_link_content
  revision_created:
    value: '1657043335'
  revision_user:
    target_id: '0'
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Mon Compte'
  description: false
  menu_name:
    value: main
  link:
    uri: 'internal:/user'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-48'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1660233950'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
2:
  id:
    value: '2'
  uuid:
    value: 767da73b-6f8c-40c9-a317-d780396d69f0
  revision_id:
    value: '2'
  langcode:
    value: fr
  bundle:
    value: menu_link_content
  revision_created:
    value: '1657043361'
  revision_user:
    target_id: '0'
  revision_log_message:
    value: ''
  enabled:
    value: '1'
  title:
    value: Recherche
  description:
    value: ''
  menu_name:
    value: main
  link:
    uri: 'internal:/search'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-50'
  expanded:
    value: '0'
  parent:
    value: ''
  changed:
    value: '1657381593'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
3:
  id:
    value: '3'
  uuid:
    value: a3778606-04e3-4700-875b-48838851ceea
  revision_id:
    value: '3'
  langcode:
    value: fr
  bundle:
    value: menu_link_content
  revision_created:
    value: '1657381963'
  revision_user:
    target_id: '0'
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Logout
  description: false
  menu_name:
    value: main
  link:
    uri: 'internal:/user/logout'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-47'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1660233950'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
4:
  id:
    value: '4'
  uuid:
    value: 5b85644d-c731-45c4-8786-97fe9501d190
  revision_id:
    value: '4'
  langcode:
    value: fr
  bundle:
    value: menu_link_content
  revision_created:
    value: '1660233945'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Nouvelle substance'
  description: false
  menu_name:
    value: main
  link:
    uri: 'internal:/node/add/substance'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '1'
  weight:
    value: '-49'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1660233950'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
