_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 5d8f3e2a-1aa7-4050-ab7f-6739e3ad56a6
name: GNLC.Chimie
mail: michele.rizzello@eduvaud.ch
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
